language: scala
sudo: false
matrix:
  include:
    # Spark 2.0.0-SNAPSHOT and Scala 2.11
    - jdk: openjdk7
      scala: 2.11.7
      env: TEST_SPARK_VERSION="2.0.0-SNAPSHOT"
    # Spark 2.0.0-SNAPSHOT and Scala 2.10
    - jdk: openjdk7
      scala: 2.10.5
      env: TEST_SPARK_VERSION="2.0.0-SNAPSHOT"
script:
  - sbt -Dspark.testVersion=$TEST_SPARK_VERSION ++$TRAVIS_SCALA_VERSION update clean coverage test examples/test
  - sbt ++$TRAVIS_SCALA_VERSION scalastyle examples/scalastyle
after_success:
  - bash <(curl -s https://codecov.io/bash)
